//
// Created by louis on 13/11/2021.
//

#ifndef HEURISTICALGORITHMSUSINGTREEDECOMPOSITIONS_DATASTRUCTURESALIASES_H
#define HEURISTICALGORITHMSUSINGTREEDECOMPOSITIONS_DATASTRUCTURESALIASES_H

namespace DataStructures
{
    using ColourType = unsigned int;
    using VertexType = unsigned int;
}

#endif //HEURISTICALGORITHMSUSINGTREEDECOMPOSITIONS_DATASTRUCTURESALIASES_H
