//
// Created by louis on 24/10/2021.
//

#ifndef HEURISTICALGORITHMSUSINGTREEDECOMPOSITIONS_CUSTOMTYPES_H
#define HEURISTICALGORITHMSUSINGTREEDECOMPOSITIONS_CUSTOMTYPES_H

using vertexType = unsigned int;
using colourType = unsigned int;

#endif //HEURISTICALGORITHMSUSINGTREEDECOMPOSITIONS_CUSTOMTYPES_H
